### ISSUE TITLE
Since year change to 2020 no longer working

### ISSUE THREAD

**Issue by alexfatkong** [marius1/home-assistant-custom-components#3]
Since the year change from 2019 to 2020 the sensors are no longer working.

Thanks in advance if this could be fixed.

Cheers,
Alex

**Comment by marius1** [comment]
Weird, mine still works fine. Any erros in the logs?

Can you try to get the data for your address manually. Get bag id via this link:
`https://apps.hvcgroep.nl/rest/adressen/<postcode>-<huisnummer>`

Then get the data via this url
`https://apps.hvcgroep.nl/rest/adressen/<bagId>/kalender/2020`
