### ISSUE TITLE
Missing manifest.json (Resolved)

### ISSUE THREAD

**Issue by Ierlandfan** [marius1/home-assistant-custom-components#4]
Since a recent change in Home Assistant every custom component needs to have a manifest.json file in the dir otherwise it errors out on "platform hvc not found"

So manual create a manifest.json in the custom_components/hvc dir and paste this into it. (And save) 

{
  "domain": "hvc",
  "name": "hvc",
  "version": "1.0.1",
  "documentation": "https://github.com/marius1/home-assistant-custom-components",
  "dependencies": [],
  "codeowners": [],
  "requirements": [],
  "iot_class": "cloud_polling"
}

**Comment by marius1** [comment]
Thanks for this! I fixed it myself same way but totally forgot to update this repo. Have done so now.
